---
on:
  pull_request:

jobs:
  build:
    runs-on: github-ubuntu-latest-s
    permissions:
      contents: read
      checks: read
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Last Check Suite
        id: check_suite
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;

            const { data: { check_suites: checkSuites }} = await github.rest.checks.listSuitesForRef({
              owner: owner,
              repo: repo,
              ref: "${{ github.base_ref }}",
            });

            core.setOutput("last_check_suite_id", checkSuites[0].id);

      - name: Self test
        id: selftest
        env:
          GITHUB_CHECK_SUITE_ID: ${{ steps.check_suite.outputs.last_check_suite_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./
        with:
          slackChannel: 'squad-eng-xp-tests'
