---
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest-large
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version-file: pyproject.toml
          cache: 'poetry'

      - name: Test
        run: |
          poetry install
          poetry run pytest
